<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>9.0</LangVersion>

    <IsPackable>false</IsPackable>

    <RootNamespace>Rasa.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.11.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.11.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rasa.Auth\Rasa.Auth.csproj" />
    <ProjectReference Include="..\Rasa.Utils\Rasa.Utils.csproj" />
  </ItemGroup>

</Project>
